# Generated by Django 5.1.5 on 2025-02-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomeexpensetable',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
