# Generated by Django 5.1.2 on 2024-11-23 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logintable',
            name='status',
            field=models.CharField(blank=True, default='REJECT', max_length=30, null=True),
        ),
    ]
