# Generated by Django 5.1.2 on 2024-12-27 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_logintable_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction_id',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(blank=True, null=True)),
                ('Amount', models.FloatField(blank=True, null=True)),
                ('receiver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='myapp.usertable')),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='myapp.usertable')),
            ],
        ),
    ]
