# Generated by Django 5.1.2 on 2024-12-27 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_transaction_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction_id',
            new_name='TransactionTable',
        ),
    ]
