# Generated by Django 5.1.5 on 2025-02-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_incomeexpensetable_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomeexpensetable',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='incomeexpensetable',
            name='Date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
