# Generated by Django 5.1.2 on 2024-12-28 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_transaction_id_transactiontable'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='Address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usertable',
            name='Totalincome',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
