# Generated by Django 5.1.2 on 2024-12-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_usertable_address_usertable_totalincome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='Email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='Totalincome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
