# Generated by Django 5.1.2 on 2025-01-18 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_usertable_email_alter_usertable_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomeexpensetable',
            name='Category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='incomeexpensetable',
            name='Price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='incomeexpensetable',
            name='Quantity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
