# Generated by Django 5.1.2 on 2025-01-18 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_notificationtable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedbackTable',
        ),
    ]
