# Generated by Django 5.1.2 on 2025-01-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_delete_feedbacktable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomeexpensetable',
            name='Price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
