# Generated by Django 5.1.2 on 2025-01-18 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_incomeexpensetable_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomeexpensetable',
            name='BUDGET',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.budgettable'),
        ),
        migrations.AlterField(
            model_name='incomeexpensetable',
            name='USER',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.usertable'),
        ),
    ]
